# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.session::wakasession.form_name

# Model Form Field configuration
form: $/waka/session/models/wakasession/fields.yaml

# Model Class name
modelClass: Waka\Session\Models\WakaSession

# Default redirect location
defaultRedirect: waka/session/wakasessions

# Create page
create:
    title: waka.session::wakasession.create
    redirect: waka/session/wakasessions/update/:id
    redirectClose: waka/session/wakasessions
    form: $/waka/session/models/wakasession/fields_create.yaml

# Update page
update:
    title: waka.session::wakasession.update
    redirect: waka/session/wakasessions/update/:id
    redirectClose: waka/session/wakasessions

# Preview page
preview:
    title: waka.session::wakasession.preview_name
